/**
 * Global Reference Regions — CO2 Router Canonical Region Registry
 *
 * Carbon intensity: EIA-930, GB Carbon API, Energi Data, Fingrid, Ember, IEA WEO 2023-2024
 * Latency: AWS/GCP/Azure published p50 inter-region RTT
 * Cost: IEA/OECD industrial electricity price averages (USD/kWh)
 * Renewable capacity: IRENA + national grid operator published figures
 * Water stress: Aqueduct 4.0 baseline water stress index (WRI, free)
 *
 * All data publicly available, free to use, owned by CO2 Router.
 * Sources: eia.gov, ember-climate.org, iea.org, irena.org, wri.org/aqueduct
 */

export type RegionCode =
  // North America
  | 'US-CAL-CISO'
  | 'US-TEX-ERCO'
  | 'US-MIDA-PJM'
  | 'US-MIDW-MISO'
  | 'US-NW-BPAT'
  | 'US-NE-ISNE'
  | 'CA-QC'
  | 'CA-ON'
  | 'CA-BC'
  // Europe
  | 'EU-GB'
  | 'EU-FR'
  | 'EU-DE'
  | 'EU-SE'
  | 'EU-NO'
  | 'EU-FI'
  | 'EU-DK1'
  | 'EU-DK2'
  | 'EU-NL'
  | 'EU-BE'
  | 'EU-ES'
  | 'EU-PT'
  | 'EU-IT'
  | 'EU-PL'
  | 'EU-CH'
  | 'EU-AT'
  // Asia Pacific
  | 'AP-SG'
  | 'AP-JP-TOKYO'
  | 'AP-JP-OSAKA'
  | 'AP-AU-NSW'
  | 'AP-AU-VIC'
  | 'AP-AU-QLD'
  | 'AP-AU-SA'
  | 'AP-IN-SOUTH'
  | 'AP-IN-WEST'
  | 'AP-KR'
  | 'AP-TW'
  // South America
  | 'SA-BR-SE'
  | 'SA-BR-S'
  | 'SA-CL-SEN'
  | 'SA-CO'
  // Africa / Middle East
  | 'AF-ZA'
  | 'ME-AE'

export interface GlobalRegionConfig {
  regionCode: RegionCode
  displayName: string
  country: string
  cloudRegions: string[]
  balancingAuthority: string | null
  avgCarbonIntensity: number
  typicalLatencyMs: number
  costPerKwh: number
  renewableCapacity: number
  waterStressIndex: number | null
  wattTimeZone?: string
  eiaRespondent?: string
  gridZone?: string
  estimatedFlag: boolean
  syntheticFlag: boolean
  notes?: string
}

/** @deprecated Use GlobalRegionConfig */
export type ReferenceRegion = GlobalRegionConfig

export const REFERENCE_REGIONS: GlobalRegionConfig[] = [

  // ── North America — US ──

  {
    regionCode: 'US-CAL-CISO',
    displayName: 'US California (CAISO)',
    country: 'US',
    cloudRegions: ['us-west-1', 'sfo1'],
    balancingAuthority: 'CISO',
    avgCarbonIntensity: 260,
    typicalLatencyMs: 55,
    costPerKwh: 0.20,
    renewableCapacity: 55,
    waterStressIndex: 0.8,
    wattTimeZone: 'CAISO_NORTH',
    eiaRespondent: 'CISO',
    gridZone: 'US-CAL-CISO',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'CAISO. High solar + gas. WattTime MOER free tier covers CAISO_NORTH.',
  },
  {
    regionCode: 'US-TEX-ERCO',
    displayName: 'US Texas (ERCOT)',
    country: 'US',
    cloudRegions: ['southcentralus'],
    balancingAuthority: 'ERCO',
    avgCarbonIntensity: 430,
    typicalLatencyMs: 45,
    costPerKwh: 0.10,
    renewableCapacity: 45,
    waterStressIndex: 0.7,
    wattTimeZone: 'ERCOT_EASTTX',
    eiaRespondent: 'ERCO',
    gridZone: 'US-TEX-ERCO',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'ERCOT isolated grid. Fast-growing wind but still gas-heavy.',
  },
  {
    regionCode: 'US-MIDA-PJM',
    displayName: 'US Mid-Atlantic (PJM)',
    country: 'US',
    cloudRegions: ['us-east-1', 'us-east-2', 'iad1', 'eastus', 'eastus2', 'us-east4'],
    balancingAuthority: 'PJM',
    avgCarbonIntensity: 420,
    typicalLatencyMs: 35,
    costPerKwh: 0.12,
    renewableCapacity: 25,
    waterStressIndex: 0.4,
    wattTimeZone: 'PJM_DOM',
    eiaRespondent: 'PJM',
    gridZone: 'US-MIDA-PJM',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'Largest US BA. Heavy gas + nuclear. Primary AWS/GCP/Azure east coast zone.',
  },
  {
    regionCode: 'US-MIDW-MISO',
    displayName: 'US Midwest (MISO)',
    country: 'US',
    cloudRegions: ['us-central-1', 'cle1', 'us-central1', 'centralus'],
    balancingAuthority: 'MISO',
    avgCarbonIntensity: 480,
    typicalLatencyMs: 40,
    costPerKwh: 0.11,
    renewableCapacity: 30,
    waterStressIndex: 0.5,
    wattTimeZone: 'MISO_WUMS',
    eiaRespondent: 'MISO',
    gridZone: 'US-MIDW-MISO',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'MISO covers midwest. High wind capacity but still significant coal.',
  },
  {
    regionCode: 'US-NW-BPAT',
    displayName: 'US Northwest (BPA)',
    country: 'US',
    cloudRegions: ['us-west-2', 'pdx1', 'us-west1', 'westus2'],
    balancingAuthority: 'BPAT',
    avgCarbonIntensity: 220,
    typicalLatencyMs: 40,
    costPerKwh: 0.09,
    renewableCapacity: 65,
    waterStressIndex: 0.3,
    wattTimeZone: 'BPAT',
    eiaRespondent: 'BPAT',
    gridZone: 'US-NW-BPAT',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'BPA. Predominantly hydro + wind. One of cleanest US zones.',
  },
  {
    regionCode: 'US-NE-ISNE',
    displayName: 'US Northeast (ISO-NE)',
    country: 'US',
    cloudRegions: [],
    balancingAuthority: 'ISNE',
    avgCarbonIntensity: 300,
    typicalLatencyMs: 40,
    costPerKwh: 0.18,
    renewableCapacity: 35,
    waterStressIndex: 0.5,
    wattTimeZone: 'ISNE',
    eiaRespondent: 'ISNE',
    gridZone: 'US-NE-ISNE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'ISO New England. Nuclear + offshore wind heavy.',
  },

  // ── Canada ──

  {
    regionCode: 'CA-QC',
    displayName: 'Canada Quebec (Hydro-Quebec)',
    country: 'CA',
    cloudRegions: ['ca-central-1', 'yul1', 'northamerica-northeast1', 'canadaeast'],
    balancingAuthority: 'CA-QC',
    avgCarbonIntensity: 20,
    typicalLatencyMs: 40,
    costPerKwh: 0.07,
    renewableCapacity: 98,
    waterStressIndex: 0.2,
    gridZone: 'CA-QC',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Hydro-Quebec. Nearly 100% hydroelectric. Cleanest major grid in North America.',
  },
  {
    regionCode: 'CA-ON',
    displayName: 'Canada Ontario (IESO)',
    country: 'CA',
    cloudRegions: ['canadacentral'],
    balancingAuthority: 'CA-ON',
    avgCarbonIntensity: 80,
    typicalLatencyMs: 45,
    costPerKwh: 0.11,
    renewableCapacity: 65,
    waterStressIndex: 0.3,
    gridZone: 'CA-ON',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Ontario IESO. Nuclear dominant (~60%) + hydro.',
  },
  {
    regionCode: 'CA-BC',
    displayName: 'Canada British Columbia (BC Hydro)',
    country: 'CA',
    cloudRegions: [],
    balancingAuthority: 'CA-BC',
    avgCarbonIntensity: 30,
    typicalLatencyMs: 55,
    costPerKwh: 0.09,
    renewableCapacity: 95,
    waterStressIndex: 0.3,
    gridZone: 'CA-BC',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'BC Hydro. Predominantly run-of-river hydro. Extremely clean grid.',
  },

  // ── Europe ──

  {
    regionCode: 'EU-GB',
    displayName: 'UK Great Britain',
    country: 'GB',
    cloudRegions: ['eu-west-2', 'lhr1'],
    balancingAuthority: 'GB',
    avgCarbonIntensity: 220,
    typicalLatencyMs: 25,
    costPerKwh: 0.25,
    renewableCapacity: 50,
    waterStressIndex: 0.4,
    gridZone: 'GB',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'National Grid ESO. GB Carbon Intensity API free, 96h forecast. Wind + nuclear.',
  },
  {
    regionCode: 'EU-FR',
    displayName: 'France (RTE)',
    country: 'FR',
    cloudRegions: ['eu-west-3', 'cdg1', 'europe-west9', 'francecentral'],
    balancingAuthority: 'FR',
    avgCarbonIntensity: 60,
    typicalLatencyMs: 30,
    costPerKwh: 0.23,
    renewableCapacity: 80,
    waterStressIndex: 0.5,
    gridZone: 'FR',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'RTE. ~70% nuclear. One of lowest carbon intensities in Europe.',
  },
  {
    regionCode: 'EU-DE',
    displayName: 'Germany',
    country: 'DE',
    cloudRegions: ['eu-central-1', 'fra1'],
    balancingAuthority: 'DE',
    avgCarbonIntensity: 350,
    typicalLatencyMs: 30,
    costPerKwh: 0.30,
    renewableCapacity: 55,
    waterStressIndex: 0.5,
    gridZone: 'DE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AWS eu-central-1. High lignite + solar/wind mix. Transitional grid.',
  },
  {
    regionCode: 'EU-SE',
    displayName: 'Sweden (Svenska Kraftnat)',
    country: 'SE',
    cloudRegions: ['eu-north-1', 'arn1', 'swedencentral'],
    balancingAuthority: 'SE',
    avgCarbonIntensity: 40,
    typicalLatencyMs: 35,
    costPerKwh: 0.22,
    renewableCapacity: 90,
    waterStressIndex: 0.3,
    gridZone: 'SE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AWS eu-north-1. Nuclear + hydro. One of cleanest grids in Europe.',
  },
  {
    regionCode: 'EU-NO',
    displayName: 'Norway (Statnett)',
    country: 'NO',
    cloudRegions: ['norwayeast'],
    balancingAuthority: 'NO',
    avgCarbonIntensity: 20,
    typicalLatencyMs: 40,
    costPerKwh: 0.18,
    renewableCapacity: 98,
    waterStressIndex: 0.2,
    gridZone: 'NO',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Statnett. Nearly 100% hydro. Cheapest and cleanest in Europe.',
  },
  {
    regionCode: 'EU-FI',
    displayName: 'Finland (Fingrid)',
    country: 'FI',
    cloudRegions: ['europe-north1'],
    balancingAuthority: 'FI',
    avgCarbonIntensity: 90,
    typicalLatencyMs: 40,
    costPerKwh: 0.22,
    renewableCapacity: 75,
    waterStressIndex: 0.4,
    gridZone: 'FI',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'Fingrid API free (key required). Nuclear + hydro + wind.',
  },
  {
    regionCode: 'EU-DK1',
    displayName: 'Denmark West (DK1)',
    country: 'DK',
    cloudRegions: [],
    balancingAuthority: 'DK1',
    avgCarbonIntensity: 180,
    typicalLatencyMs: 35,
    costPerKwh: 0.29,
    renewableCapacity: 70,
    waterStressIndex: 0.4,
    gridZone: 'DK-DK1',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'Energi Data Service free API. DK1 west zone. High wind, gas backup.',
  },
  {
    regionCode: 'EU-DK2',
    displayName: 'Denmark East (DK2)',
    country: 'DK',
    cloudRegions: [],
    balancingAuthority: 'DK2',
    avgCarbonIntensity: 180,
    typicalLatencyMs: 35,
    costPerKwh: 0.29,
    renewableCapacity: 70,
    waterStressIndex: 0.4,
    gridZone: 'DK-DK2',
    estimatedFlag: false,
    syntheticFlag: false,
    notes: 'Energi Data Service free API. DK2 east zone. More Nordic hydro imports than DK1.',
  },
  {
    regionCode: 'EU-NL',
    displayName: 'Netherlands (TenneT NL)',
    country: 'NL',
    cloudRegions: ['westeurope'],
    balancingAuthority: 'NL',
    avgCarbonIntensity: 400,
    typicalLatencyMs: 30,
    costPerKwh: 0.27,
    renewableCapacity: 35,
    waterStressIndex: 0.5,
    gridZone: 'NL',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'TenneT NL. Gas-heavy with growing offshore wind.',
  },
  {
    regionCode: 'EU-BE',
    displayName: 'Belgium (Elia)',
    country: 'BE',
    cloudRegions: ['europe-west1'],
    balancingAuthority: 'BE',
    avgCarbonIntensity: 250,
    typicalLatencyMs: 30,
    costPerKwh: 0.27,
    renewableCapacity: 45,
    waterStressIndex: 0.5,
    gridZone: 'BE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Elia. Nuclear + offshore wind. GCP europe-west1.',
  },
  {
    regionCode: 'EU-ES',
    displayName: 'Spain (REE)',
    country: 'ES',
    cloudRegions: [],
    balancingAuthority: 'ES',
    avgCarbonIntensity: 200,
    typicalLatencyMs: 40,
    costPerKwh: 0.24,
    renewableCapacity: 55,
    waterStressIndex: 0.6,
    gridZone: 'ES',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Red Electrica. High solar + wind + nuclear.',
  },
  {
    regionCode: 'EU-PT',
    displayName: 'Portugal (REN)',
    country: 'PT',
    cloudRegions: [],
    balancingAuthority: 'PT',
    avgCarbonIntensity: 150,
    typicalLatencyMs: 45,
    costPerKwh: 0.23,
    renewableCapacity: 60,
    waterStressIndex: 0.5,
    gridZone: 'PT',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'REN Portugal. High wind + hydro. Growing solar.',
  },
  {
    regionCode: 'EU-IT',
    displayName: 'Italy (Terna)',
    country: 'IT',
    cloudRegions: [],
    balancingAuthority: 'IT',
    avgCarbonIntensity: 330,
    typicalLatencyMs: 45,
    costPerKwh: 0.28,
    renewableCapacity: 40,
    waterStressIndex: 0.6,
    gridZone: 'IT-NO',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Terna Italy North zone. Gas + hydro + solar mix.',
  },
  {
    regionCode: 'EU-PL',
    displayName: 'Poland (PSE)',
    country: 'PL',
    cloudRegions: [],
    balancingAuthority: 'PL',
    avgCarbonIntensity: 700,
    typicalLatencyMs: 50,
    costPerKwh: 0.22,
    renewableCapacity: 20,
    waterStressIndex: 0.5,
    gridZone: 'PL',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'PSE. Coal-dominant. Highest carbon in EU. Route away when possible.',
  },
  {
    regionCode: 'EU-CH',
    displayName: 'Switzerland (Swissgrid)',
    country: 'CH',
    cloudRegions: [],
    balancingAuthority: 'CH',
    avgCarbonIntensity: 50,
    typicalLatencyMs: 35,
    costPerKwh: 0.24,
    renewableCapacity: 90,
    waterStressIndex: 0.4,
    gridZone: 'CH',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Swissgrid. Nuclear + alpine hydro. Clean transit hub for European grid.',
  },
  {
    regionCode: 'EU-AT',
    displayName: 'Austria (APG)',
    country: 'AT',
    cloudRegions: [],
    balancingAuthority: 'AT',
    avgCarbonIntensity: 150,
    typicalLatencyMs: 35,
    costPerKwh: 0.26,
    renewableCapacity: 70,
    waterStressIndex: 0.4,
    gridZone: 'AT',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'APG Austria. Hydro-dominant + imports. Clean for Central Europe.',
  },

  // ── Asia Pacific ──

  {
    regionCode: 'AP-SG',
    displayName: 'Singapore (EMA)',
    country: 'SG',
    cloudRegions: ['ap-southeast-1', 'sin1'],
    balancingAuthority: 'SG',
    avgCarbonIntensity: 550,
    typicalLatencyMs: 70,
    costPerKwh: 0.24,
    renewableCapacity: 10,
    waterStressIndex: 0.8,
    gridZone: 'SG',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'EMA Singapore. Gas-dominant city-state. No available solar land area.',
  },
  {
    regionCode: 'AP-JP-TOKYO',
    displayName: 'Japan Tokyo (TEPCO)',
    country: 'JP',
    cloudRegions: ['ap-northeast-1', 'hnd1', 'japaneast'],
    balancingAuthority: 'JP-TK',
    avgCarbonIntensity: 450,
    typicalLatencyMs: 80,
    costPerKwh: 0.28,
    renewableCapacity: 25,
    waterStressIndex: 0.6,
    gridZone: 'JP-TK',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'TEPCO. Post-Fukushima LNG-heavy. AWS ap-northeast-1.',
  },
  {
    regionCode: 'AP-JP-OSAKA',
    displayName: 'Japan Osaka (Kansai)',
    country: 'JP',
    cloudRegions: ['ap-northeast-3', 'kix1'],
    balancingAuthority: 'JP-OS',
    avgCarbonIntensity: 450,
    typicalLatencyMs: 85,
    costPerKwh: 0.28,
    renewableCapacity: 25,
    waterStressIndex: 0.6,
    gridZone: 'JP-KN',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Kansai Electric. More nuclear than TEPCO. AWS ap-northeast-3.',
  },
  {
    regionCode: 'AP-AU-NSW',
    displayName: 'Australia NSW (AEMO)',
    country: 'AU',
    cloudRegions: ['ap-southeast-2', 'syd1', 'australiaeast'],
    balancingAuthority: 'AU-NSW',
    avgCarbonIntensity: 600,
    typicalLatencyMs: 110,
    costPerKwh: 0.26,
    renewableCapacity: 30,
    waterStressIndex: 0.7,
    gridZone: 'AU-NSW',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AEMO NEM NSW. Coal-heavy but rapid renewable transition.',
  },
  {
    regionCode: 'AP-AU-VIC',
    displayName: 'Australia Victoria (AEMO)',
    country: 'AU',
    cloudRegions: [],
    balancingAuthority: 'AU-VIC',
    avgCarbonIntensity: 650,
    typicalLatencyMs: 115,
    costPerKwh: 0.26,
    renewableCapacity: 25,
    waterStressIndex: 0.7,
    gridZone: 'AU-VIC',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AEMO NEM VIC. Brown coal heavy.',
  },
  {
    regionCode: 'AP-AU-QLD',
    displayName: 'Australia Queensland (AEMO)',
    country: 'AU',
    cloudRegions: [],
    balancingAuthority: 'AU-QLD',
    avgCarbonIntensity: 700,
    typicalLatencyMs: 120,
    costPerKwh: 0.24,
    renewableCapacity: 20,
    waterStressIndex: 0.7,
    gridZone: 'AU-QLD',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AEMO NEM QLD. Coal-dominant. Rapid solar build-out underway.',
  },
  {
    regionCode: 'AP-AU-SA',
    displayName: 'Australia South Australia (AEMO)',
    country: 'AU',
    cloudRegions: [],
    balancingAuthority: 'AU-SA',
    avgCarbonIntensity: 500,
    typicalLatencyMs: 120,
    costPerKwh: 0.30,
    renewableCapacity: 50,
    waterStressIndex: 0.7,
    gridZone: 'AU-SA',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'AEMO NEM SA. Highest renewable % in Australian NEM. Wind + solar heavy.',
  },
  {
    regionCode: 'AP-IN-SOUTH',
    displayName: 'India South (SRLDC)',
    country: 'IN',
    cloudRegions: ['ap-south-1'],
    balancingAuthority: 'IN-SOUTH',
    avgCarbonIntensity: 750,
    typicalLatencyMs: 90,
    costPerKwh: 0.10,
    renewableCapacity: 20,
    waterStressIndex: 0.9,
    gridZone: 'IN-SO',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Southern RLDC. Higher solar penetration than west India.',
  },
  {
    regionCode: 'AP-IN-WEST',
    displayName: 'India West (WRLDC)',
    country: 'IN',
    cloudRegions: [],
    balancingAuthority: 'IN-WEST',
    avgCarbonIntensity: 750,
    typicalLatencyMs: 95,
    costPerKwh: 0.10,
    renewableCapacity: 20,
    waterStressIndex: 0.9,
    gridZone: 'IN-WE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Western Regional Load Despatch Centre. Coal-dominant. Mumbai zone.',
  },
  {
    regionCode: 'AP-KR',
    displayName: 'South Korea (KEPCO)',
    country: 'KR',
    cloudRegions: ['ap-northeast-2', 'koreacentral'],
    balancingAuthority: 'KR',
    avgCarbonIntensity: 550,
    typicalLatencyMs: 75,
    costPerKwh: 0.25,
    renewableCapacity: 20,
    waterStressIndex: 0.7,
    gridZone: 'KR',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'KEPCO. Nuclear + coal + gas mix.',
  },
  {
    regionCode: 'AP-TW',
    displayName: 'Taiwan (Taipower)',
    country: 'TW',
    cloudRegions: [],
    balancingAuthority: 'TW',
    avgCarbonIntensity: 600,
    typicalLatencyMs: 80,
    costPerKwh: 0.24,
    renewableCapacity: 20,
    waterStressIndex: 0.7,
    gridZone: 'TW',
    estimatedFlag: true,
    syntheticFlag: true,
    notes: 'Taipower. Coal + gas + nuclear. No direct provider API coverage yet.',
  },

  // ── South America ──

  {
    regionCode: 'SA-BR-SE',
    displayName: 'Brazil Southeast (ONS)',
    country: 'BR',
    cloudRegions: ['sa-east-1', 'gru1', 'southamerica-east1', 'brazilsouth'],
    balancingAuthority: 'BR-SE',
    avgCarbonIntensity: 100,
    typicalLatencyMs: 130,
    costPerKwh: 0.14,
    renewableCapacity: 75,
    waterStressIndex: 0.6,
    gridZone: 'BR-SE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Brazil SIN southeast/center-west. Dominated by large hydro + growing wind/solar.',
  },
  {
    regionCode: 'SA-BR-S',
    displayName: 'Brazil South (ONS)',
    country: 'BR',
    cloudRegions: [],
    balancingAuthority: 'BR-S',
    avgCarbonIntensity: 120,
    typicalLatencyMs: 130,
    costPerKwh: 0.14,
    renewableCapacity: 75,
    waterStressIndex: 0.6,
    gridZone: 'BR-S',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Brazil SIN south sub-region. High wind penetration from Rio Grande do Sul.',
  },
  {
    regionCode: 'SA-CL-SEN',
    displayName: 'Chile (CEN)',
    country: 'CL',
    cloudRegions: [],
    balancingAuthority: 'CL-SEN',
    avgCarbonIntensity: 350,
    typicalLatencyMs: 140,
    costPerKwh: 0.16,
    renewableCapacity: 45,
    waterStressIndex: 0.8,
    gridZone: 'CL-SEN',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Chilean national grid. Rapid solar build-out in Atacama. Gas still significant.',
  },
  {
    regionCode: 'SA-CO',
    displayName: 'Colombia (XM)',
    country: 'CO',
    cloudRegions: [],
    balancingAuthority: 'CO',
    avgCarbonIntensity: 100,
    typicalLatencyMs: 140,
    costPerKwh: 0.13,
    renewableCapacity: 75,
    waterStressIndex: 0.7,
    gridZone: 'CO',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Colombian SIN. Hydro-dominant but exposed to El Nino drought risk.',
  },

  // ── Africa / Middle East ──

  {
    regionCode: 'AF-ZA',
    displayName: 'South Africa (Eskom)',
    country: 'ZA',
    cloudRegions: ['af-south-1', 'cpt1'],
    balancingAuthority: 'ZA',
    avgCarbonIntensity: 800,
    typicalLatencyMs: 130,
    costPerKwh: 0.15,
    renewableCapacity: 10,
    waterStressIndex: 0.8,
    gridZone: 'ZA',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'Eskom. Coal-dominant grid. Route only if latency-critical for SA.',
  },
  {
    regionCode: 'ME-AE',
    displayName: 'United Arab Emirates (TRANSCO)',
    country: 'AE',
    cloudRegions: ['me-central-1', 'dxb1'],
    balancingAuthority: 'AE',
    avgCarbonIntensity: 550,
    typicalLatencyMs: 120,
    costPerKwh: 0.10,
    renewableCapacity: 10,
    waterStressIndex: 0.9,
    gridZone: 'AE',
    estimatedFlag: true,
    syntheticFlag: false,
    notes: 'UAE TRANSCO. Gas-dominant. Low cost but high carbon. Barakah nuclear online.',
  },
]