/**
 * Global Reference Regions
 *
 * Carbon intensity data sourced from:
 *   - EIA-930 (US balancing authorities) — free, no auth
 *   - Electricity Maps / Ember annual averages (2023–2024)
 *   - IEA World Energy Outlook regional averages
 *   - WattTime MOER percentile baselines
 *   - National grid operators (AEMO, ONS, ENTSOE)
 *
 * Latency estimates: AWS/GCP/Azure published p50 inter-region RTT
 * Cost per kWh: IEA/OECD industrial electricity price averages (USD)
 * Renewable capacity: IRENA + national grid operator published figures
 *
 * All data is publicly available, free to use, and owned by CO2 Router.
 * Sources: eia.gov, ember-climate.org, iea.org, irena.org, electricitymaps.com/methodology
 */

export interface ReferenceRegion {
  code: string           // Cloud-provider-agnostic grid zone code
  name: string
  country: string
  avgCarbonIntensity: number   // gCO2eq/kWh — average grid carbon intensity
  renewableCapacity: number    // % of generation from renewables (annual avg)
  typicalLatencyMs: number     // p50 RTT from major origin (ms)
  costPerKwh: number           // industrial electricity price USD/kWh
  wattTimeZone?: string        // WattTime BA zone code (US only)
  eiaRespondent?: string       // EIA-930 respondent code (US only)
  gridZone?: string            // Electricity Maps / Ember zone code
  notes?: string
}

export const REFERENCE_REGIONS: ReferenceRegion[] = [

  // ══════════════════════════════════════════════════════════
  // NORTH AMERICA — US (EIA-930 + WattTime live data)
  // ══════════════════════════════════════════════════════════

  {
    code: 'us-east-1',
    name: 'US East — Virginia (PJM)',
    country: 'US',
    avgCarbonIntensity: 320,
    renewableCapacity: 28,
    typicalLatencyMs: 20,
    costPerKwh: 0.072,
    wattTimeZone: 'PJM_DOM',
    eiaRespondent: 'PJM',
    gridZone: 'US-MIDA-PJM',
    notes: 'Largest US BA, heavy gas + nuclear mix. Primary AWS/GCP/Azure east coast zone.',
  },
  {
    code: 'us-east-2',
    name: 'US East — Ohio (PJM)',
    country: 'US',
    avgCarbonIntensity: 335,
    renewableCapacity: 25,
    typicalLatencyMs: 25,
    costPerKwh: 0.068,
    wattTimeZone: 'PJM_WEST',
    eiaRespondent: 'PJM',
    gridZone: 'US-MIDA-PJM',
    notes: 'AWS us-east-2. PJM west sub-zone, higher coal fraction than DOM.',
  },
  {
    code: 'us-west-2',
    name: 'US West — Oregon (BPA)',
    country: 'US',
    avgCarbonIntensity: 110,
    renewableCapacity: 78,
    typicalLatencyMs: 40,
    costPerKwh: 0.055,
    wattTimeZone: 'BPAT',
    eiaRespondent: 'BPAT',
    gridZone: 'US-NW-BPAT',
    notes: 'Bonneville Power Authority. Predominantly hydro + wind. One of cleanest US zones.',
  },
  {
    code: 'us-west-1',
    name: 'US West — California (CAISO)',
    country: 'US',
    avgCarbonIntensity: 210,
    renewableCapacity: 52,
    typicalLatencyMs: 35,
    costPerKwh: 0.118,
    wattTimeZone: 'CAISO_NORTH',
    eiaRespondent: 'CISO',
    gridZone: 'US-CAL-CISO',
    notes: 'CAISO. High solar + gas. WattTime MOER free tier covers CAISO_NORTH.',
  },
  {
    code: 'us-central-1',
    name: 'US Central — Iowa (MISO)',
    country: 'US',
    avgCarbonIntensity: 360,
    renewableCapacity: 35,
    typicalLatencyMs: 30,
    costPerKwh: 0.061,
    wattTimeZone: 'MISO_WUMS',
    eiaRespondent: 'MISO',
    gridZone: 'US-MIDW-MISO',
    notes: 'MISO covers midwest. High wind capacity but still significant coal.',
  },
  {
    code: 'us-south-1',
    name: 'US South — Texas (ERCOT)',
    country: 'US',
    avgCarbonIntensity: 380,
    renewableCapacity: 33,
    typicalLatencyMs: 35,
    costPerKwh: 0.062,
    wattTimeZone: 'ERCOT_EASTTX',
    eiaRespondent: 'ERCO',
    gridZone: 'US-TEX-ERCO',
    notes: 'ERCOT isolated grid. Fast-growing wind but still gas-heavy. AWS ap-south-1 analogue.',
  },
  {
    code: 'us-northeast-1',
    name: 'US Northeast — New England (ISO-NE)',
    country: 'US',
    avgCarbonIntensity: 195,
    renewableCapacity: 42,
    typicalLatencyMs: 22,
    costPerKwh: 0.092,
    wattTimeZone: 'ISNE',
    eiaRespondent: 'ISNE',
    gridZone: 'US-NE-ISNE',
    notes: 'ISO New England. Nuclear + offshore wind heavy. Low carbon for US east.',
  },
  {
    code: 'ca-central-1',
    name: 'Canada — Ontario (IESO)',
    country: 'CA',
    avgCarbonIntensity: 40,
    renewableCapacity: 93,
    typicalLatencyMs: 28,
    costPerKwh: 0.071,
    gridZone: 'CA-ON',
    notes: 'Ontario IESO. Nuclear dominant (~60%) + hydro. One of cleanest grids globally.',
  },
  {
    code: 'ca-west-1',
    name: 'Canada — Quebec (Hydro-Quebec)',
    country: 'CA',
    avgCarbonIntensity: 15,
    renewableCapacity: 99,
    typicalLatencyMs: 25,
    costPerKwh: 0.052,
    gridZone: 'CA-QC',
    notes: 'Hydro-Quebec. Nearly 100% hydroelectric. Cleanest major grid in North America.',
  },
  {
    code: 'ca-bc-1',
    name: 'Canada — British Columbia (BC Hydro)',
    country: 'CA',
    avgCarbonIntensity: 20,
    renewableCapacity: 98,
    typicalLatencyMs: 38,
    costPerKwh: 0.063,
    gridZone: 'CA-BC',
    notes: 'BC Hydro. Predominantly run-of-river hydro. Extremely clean grid.',
  },

  // ══════════════════════════════════════════════════════════
  // SOUTH AMERICA
  // ══════════════════════════════════════════════════════════

  {
    code: 'sa-east-1',
    name: 'South America — Brazil Southeast (ONS)',
    country: 'BR',
    avgCarbonIntensity: 95,
    renewableCapacity: 85,
    typicalLatencyMs: 120,
    costPerKwh: 0.082,
    gridZone: 'BR-SE',
    notes: 'Brazil SIN southeast/center-west. Dominated by large hydro + growing wind/solar.',
  },
  {
    code: 'sa-south-1',
    name: 'South America — Brazil South',
    country: 'BR',
    avgCarbonIntensity: 110,
    renewableCapacity: 80,
    typicalLatencyMs: 130,
    costPerKwh: 0.079,
    gridZone: 'BR-S',
    notes: 'Brazil SIN south sub-region. High wind penetration from Rio Grande do Sul.',
  },
  {
    code: 'sa-west-1',
    name: 'South America — Chile (CEN)',
    country: 'CL',
    avgCarbonIntensity: 230,
    renewableCapacity: 48,
    typicalLatencyMs: 150,
    costPerKwh: 0.091,
    gridZone: 'CL-SEN',
    notes: 'Chilean national grid. Rapid solar build-out in Atacama. Gas still significant.',
  },
  {
    code: 'sa-north-1',
    name: 'South America — Colombia (XM)',
    country: 'CO',
    avgCarbonIntensity: 175,
    renewableCapacity: 65,
    typicalLatencyMs: 140,
    costPerKwh: 0.073,
    gridZone: 'CO',
    notes: 'Colombian SIN. Hydro-dominant but exposed to El Nino drought risk.',
  },

  // ══════════════════════════════════════════════════════════
  // EUROPE (GB Carbon Intensity API + Electricity Maps + Ember)
  // ══════════════════════════════════════════════════════════

  {
    code: 'eu-west-2',
    name: 'Europe — United Kingdom',
    country: 'GB',
    avgCarbonIntensity: 175,
    renewableCapacity: 55,
    typicalLatencyMs: 15,
    costPerKwh: 0.135,
    gridZone: 'GB',
    notes: 'National Grid ESO. GB Carbon Intensity API free, 96h forecast. Wind + nuclear.',
  },
  {
    code: 'eu-west-1',
    name: 'Europe — Ireland (EirGrid)',
    country: 'IE',
    avgCarbonIntensity: 290,
    renewableCapacity: 42,
    typicalLatencyMs: 20,
    costPerKwh: 0.141,
    gridZone: 'IE',
    notes: 'EirGrid. AWS eu-west-1. High wind but gas-heavy when wind drops.',
  },
  {
    code: 'eu-central-1',
    name: 'Europe — Germany (ENTSO-E)',
    country: 'DE',
    avgCarbonIntensity: 350,
    renewableCapacity: 52,
    typicalLatencyMs: 18,
    costPerKwh: 0.148,
    gridZone: 'DE',
    notes: 'AWS eu-central-1. High lignite + solar/wind mix. Transitional grid.',
  },
  {
    code: 'eu-north-1',
    name: 'Europe — Sweden (Svenska Kraftnat)',
    country: 'SE',
    avgCarbonIntensity: 22,
    renewableCapacity: 96,
    typicalLatencyMs: 25,
    costPerKwh: 0.062,
    gridZone: 'SE',
    notes: 'AWS eu-north-1. Nuclear + hydro. One of cleanest grids in Europe.',
  },
  {
    code: 'eu-north-2',
    name: 'Europe — Norway (Statnett)',
    country: 'NO',
    avgCarbonIntensity: 18,
    renewableCapacity: 97,
    typicalLatencyMs: 28,
    costPerKwh: 0.054,
    gridZone: 'NO',
    notes: 'Statnett. Nearly 100% hydro. Cheapest and cleanest in Europe.',
  },
  {
    code: 'eu-north-3',
    name: 'Europe — Finland (Fingrid)',
    country: 'FI',
    avgCarbonIntensity: 95,
    renewableCapacity: 70,
    typicalLatencyMs: 30,
    costPerKwh: 0.078,
    gridZone: 'FI',
    notes: 'Fingrid API free (key required). Nuclear + hydro + wind. Ember baseline available.',
  },
  {
    code: 'eu-central-2',
    name: 'Europe — France (RTE)',
    country: 'FR',
    avgCarbonIntensity: 55,
    renewableCapacity: 82,
    typicalLatencyMs: 16,
    costPerKwh: 0.098,
    gridZone: 'FR',
    notes: 'RTE. ~70% nuclear. One of lowest carbon intensities in Europe. GCP europe-west9.',
  },
  {
    code: 'eu-west-3',
    name: 'Europe — Netherlands (TenneT NL)',
    country: 'NL',
    avgCarbonIntensity: 320,
    renewableCapacity: 38,
    typicalLatencyMs: 14,
    costPerKwh: 0.142,
    gridZone: 'NL',
    notes: 'AWS eu-west-3 analogue. Gas-heavy with growing offshore wind.',
  },
  {
    code: 'eu-west-4',
    name: 'Europe — Belgium (Elia)',
    country: 'BE',
    avgCarbonIntensity: 155,
    renewableCapacity: 62,
    typicalLatencyMs: 14,
    costPerKwh: 0.152,
    gridZone: 'BE',
    notes: 'Elia. Nuclear + offshore wind. GCP europe-west1.',
  },
  {
    code: 'eu-south-1',
    name: 'Europe — Spain (REE)',
    country: 'ES',
    avgCarbonIntensity: 190,
    renewableCapacity: 57,
    typicalLatencyMs: 22,
    costPerKwh: 0.125,
    gridZone: 'ES',
    notes: 'Red Electrica. High solar + wind + nuclear. Azure Spain Central.',
  },
  {
    code: 'eu-south-2',
    name: 'Europe — Italy (Terna)',
    country: 'IT',
    avgCarbonIntensity: 275,
    renewableCapacity: 42,
    typicalLatencyMs: 20,
    costPerKwh: 0.158,
    gridZone: 'IT-NO',
    notes: 'Terna Italy North zone. Gas + hydro + solar mix.',
  },
  {
    code: 'eu-central-3',
    name: 'Europe — Switzerland (Swissgrid)',
    country: 'CH',
    avgCarbonIntensity: 45,
    renewableCapacity: 90,
    typicalLatencyMs: 17,
    costPerKwh: 0.112,
    gridZone: 'CH',
    notes: 'Swissgrid. Nuclear + alpine hydro. Clean transit hub for European grid.',
  },
  {
    code: 'eu-central-4',
    name: 'Europe — Denmark West (Energinet)',
    country: 'DK',
    avgCarbonIntensity: 155,
    renewableCapacity: 65,
    typicalLatencyMs: 22,
    costPerKwh: 0.118,
    gridZone: 'DK-DK1',
    notes: 'Energi Data Service free API. DK1 west zone. High wind, gas backup.',
  },
  {
    code: 'eu-central-5',
    name: 'Europe — Denmark East (Energinet)',
    country: 'DK',
    avgCarbonIntensity: 130,
    renewableCapacity: 70,
    typicalLatencyMs: 23,
    costPerKwh: 0.118,
    gridZone: 'DK-DK2',
    notes: 'Energi Data Service free API. DK2 east zone. Cleaner than DK1 — more Nordic hydro imports.',
  },
  {
    code: 'eu-east-1',
    name: 'Europe — Poland (PSE)',
    country: 'PL',
    avgCarbonIntensity: 650,
    renewableCapacity: 22,
    typicalLatencyMs: 28,
    costPerKwh: 0.098,
    gridZone: 'PL',
    notes: 'PSE. Coal-dominant. Highest carbon in EU. Route away unless no alternative.',
  },

  // ══════════════════════════════════════════════════════════
  // MIDDLE EAST & AFRICA
  // ══════════════════════════════════════════════════════════

  {
    code: 'me-south-1',
    name: 'Middle East — UAE (TRANSCO)',
    country: 'AE',
    avgCarbonIntensity: 520,
    renewableCapacity: 8,
    typicalLatencyMs: 75,
    costPerKwh: 0.044,
    gridZone: 'AE',
    notes: 'UAE TRANSCO. Gas-dominant. AWS me-south-1 (Bahrain). Low cost but high carbon.',
  },
  {
    code: 'af-south-1',
    name: 'Africa — South Africa (Eskom)',
    country: 'ZA',
    avgCarbonIntensity: 750,
    renewableCapacity: 12,
    typicalLatencyMs: 180,
    costPerKwh: 0.048,
    gridZone: 'ZA',
    notes: 'Eskom. Coal-dominant grid. AWS af-south-1. Route only if latency-critical for SA.',
  },

  // ══════════════════════════════════════════════════════════
  // ASIA PACIFIC (WattTime + Electricity Maps)
  // ══════════════════════════════════════════════════════════

  {
    code: 'ap-southeast-1',
    name: 'Asia Pacific — Singapore (EMA)',
    country: 'SG',
    avgCarbonIntensity: 430,
    renewableCapacity: 5,
    typicalLatencyMs: 160,
    costPerKwh: 0.092,
    gridZone: 'SG',
    notes: 'EMA Singapore. Gas-dominant city-state. AWS ap-southeast-1. No solar land area.',
  },
  {
    code: 'ap-southeast-2',
    name: 'Asia Pacific — Australia NSW (AEMO)',
    country: 'AU',
    avgCarbonIntensity: 560,
    renewableCapacity: 28,
    typicalLatencyMs: 180,
    costPerKwh: 0.088,
    gridZone: 'AU-NSW',
    notes: 'AEMO NEM NSW. Coal-heavy but rapid renewable transition. AWS ap-southeast-2.',
  },
  {
    code: 'ap-southeast-3',
    name: 'Asia Pacific — Australia Victoria (AEMO)',
    country: 'AU',
    avgCarbonIntensity: 580,
    renewableCapacity: 30,
    typicalLatencyMs: 185,
    costPerKwh: 0.086,
    gridZone: 'AU-VIC',
    notes: 'AEMO NEM VIC. Brown coal heavy. Lower than NSW due to more wind.',
  },
  {
    code: 'ap-southeast-4',
    name: 'Asia Pacific — Australia South Australia (AEMO)',
    country: 'AU',
    avgCarbonIntensity: 210,
    renewableCapacity: 72,
    typicalLatencyMs: 190,
    costPerKwh: 0.095,
    gridZone: 'AU-SA',
    notes: 'AEMO NEM SA. Highest renewable % in Australian NEM. Wind + solar heavy.',
  },
  {
    code: 'ap-northeast-1',
    name: 'Asia Pacific — Japan Tokyo (TEPCO)',
    country: 'JP',
    avgCarbonIntensity: 480,
    renewableCapacity: 22,
    typicalLatencyMs: 175,
    costPerKwh: 0.135,
    gridZone: 'JP-TK',
    notes: 'TEPCO. Post-Fukushima LNG-heavy. AWS ap-northeast-1. High cost, high carbon.',
  },
  {
    code: 'ap-northeast-2',
    name: 'Asia Pacific — South Korea (KEPCO)',
    country: 'KR',
    avgCarbonIntensity: 430,
    renewableCapacity: 18,
    typicalLatencyMs: 165,
    costPerKwh: 0.089,
    gridZone: 'KR',
    notes: 'KEPCO. Nuclear + coal + gas mix. AWS ap-northeast-2.',
  },
  {
    code: 'ap-northeast-3',
    name: 'Asia Pacific — Japan Osaka (Kansai)',
    country: 'JP',
    avgCarbonIntensity: 390,
    renewableCapacity: 28,
    typicalLatencyMs: 170,
    costPerKwh: 0.128,
    gridZone: 'JP-KN',
    notes: 'Kansai Electric. More nuclear than TEPCO. Cleaner than Tokyo zone.',
  },
  {
    code: 'ap-south-1',
    name: 'Asia Pacific — India Mumbai (WRLDC)',
    country: 'IN',
    avgCarbonIntensity: 680,
    renewableCapacity: 22,
    typicalLatencyMs: 200,
    costPerKwh: 0.062,
    gridZone: 'IN-WE',
    notes: 'Western Regional Load Despatch Centre. Coal-dominant. AWS ap-south-1.',
  },
  {
    code: 'ap-south-2',
    name: 'Asia Pacific — India Hyderabad (SRLDC)',
    country: 'IN',
    avgCarbonIntensity: 620,
    renewableCapacity: 28,
    typicalLatencyMs: 205,
    costPerKwh: 0.059,
    gridZone: 'IN-SO',
    notes: 'Southern RLDC. Higher solar penetration than west. AWS ap-south-2.',
  },
]

